version: "2"
services:
  web:
    build: ./server
    image: stevealbertwong/tutorial-appserver:latest
    environment:
      - DATABASE_NAME=tutorial
      - PORT=4000
      - DATABASE='mongodb://localhost/tutorial'
      - SECRET='ThisIsATemporarySecretKey'
    networks:
      - webnet
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    #command: ["./wait-for-it.sh", "db:5432", "--", "node", "index.js"]
    command: ["npm", "start"]
    
  ## no Dockerfile for frontend since nginx instead of "react-scripts start"

  nginx:
    build: ./nginx
    image: stevealbertwong/tutorial-nginx:latest
    ## no need to volume since conf n static built in disk image
    # volumes:
    #   - ./app/nginx.conf:/etc/nginx/conf.d/nginx.conf
    #   - ./build:/build  
    ports:
      - "80:80"
    networks:
      - webnet  ## since nginx LB to app server, needs in same network
    depends_on:
      - web
    ## copy your config into official config before run nginx
    # command: /bin/bash -c "cat /etc/nginx/conf.d/mysite.template > 
        # /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    networks:
      - webnet

  mongo-seed:
    build: ./mongo
    image: stevealbertwong/tutorial-mongoseed:latest
    environment:
      # - MONGO_HOST=127.0.0.1
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    networks:
      - webnet
    volumes:
      - ./data:/data
    depends_on: 
      - web
    command:
      "mongoimport --host mongo --port 27017 --db test --mode upsert --type json --file /data/init.json --jsonArray"

networks:
  webnet:
    external: false