version: "3"
services:
  mongdb:
    ## seeded mongodb image
    image: stevealbertwong/mongo:latest
    networks: 
      - webnet
    ports:
      - "3040:27017"
  web:
    image: benawad/slack-clone-server:latest
    networks:
      - webnet
    depends_on:
      - mongdb
    # command: ["./wait-for-it.sh", "db:5432", "--", "node", "index.js"]
    command: ["node", "index.js"]
  ## no Dockerfile for frontend since nginx instead of "react-scripts start"
  nginx:
    image: nginx
    volumes:
      - ./app/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./build:/build  ## static assets, no need to Dockerfile COPY
    ports:
      - "80:80"
    networks:
      - webnet  ## since nginx LB to app server, needs in same network
    depends_on:
      - web
    ## copy your config template into official config before run nginx
    command: /bin/bash -c "cat /etc/nginx/conf.d/mysite.template > 
        /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
networks:
  webnet: