version: '2'

services:

  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"
    networks:
      - mnet

  mongo-seed:
    build: .
    image: stevealbertwong/mongoseed 
    environment:
      # - MONGO_HOST=127.0.0.1
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    networks:
      - mnet
    volumes:
      - ./data:/data
    depends_on: 
      - mongo
    command:
      "mongoimport --host mongo --port 27017 --db test --mode upsert --type json --file /data/init.json --jsonArray"
networks:
  mnet:
    external: false